
site_name: F-BOAT

nav:
    - 'index.md'
    - 'sobre.md'
    - 'contato.md'
    - 'projeto.md'


extra_css: [extra.css]

theme:
    name: mkdocs
    nav_style: dark

site_url: https://github.com/andrepaulodantas/F-BOAT

